CREATE TABLE IF NOT EXISTS BD_Users (
  Id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  Image VARCHAR(1024),
  FirstName VARCHAR(32),
  LastName VARCHAR(32),
  Email VARCHAR(64) UNIQUE NOT NULL,
  Password VARCHAR(128) NOT NULL,
  EmailConfirmed BOOLEAN DEFAULT False,
  Phone VARCHAR(15),
  Mobile VARCHAR(15),
  Newsletter BOOLEAN DEFAULT False,
  TermsAccepted BOOLEAN NOT NULL DEFAULT False,
  Active BOOLEAN NOT NULL DEFAULT True,
  LastLogin TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ResetPasswordToken VARCHAR (64),
  ResetPasswordExpires TIMESTAMP ,
  CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
